# Исследование надежности заемщиков


Во второй части проекта вы выполните шаги 3 и 4. Их вручную проверит ревьюер.
Чтобы вам не пришлось писать код заново для шагов 1 и 2, мы добавили авторские решения в ячейки с кодом. 



## Откройте таблицу и изучите общую информацию о данных

**Задание 1. Импортируйте библиотеку pandas. Считайте данные из csv-файла в датафрейм и сохраните в переменную `data`. Путь к файлу:**

`/datasets/data.csv`

In [1]:
import pandas as pd

try:
    data = pd.read_csv('/datasets/data.csv')
except:
    data = pd.read_csv('https://code.s3.yandex.net/datasets/data.csv')

**Задание 2. Выведите первые 20 строчек датафрейма `data` на экран.**

In [2]:
data.head(20)

children  days_employed  dob_years            education  education_id  \
0          1   -8437.673028         42               высшее             0   
1          1   -4024.803754         36              среднее             1   
2          0   -5623.422610         33              Среднее             1   
3          3   -4124.747207         32              среднее             1   
4          0  340266.072047         53              среднее             1   
5          0    -926.185831         27               высшее             0   
6          0   -2879.202052         43               высшее             0   
7          0    -152.779569         50              СРЕДНЕЕ             1   
8          2   -6929.865299         35               ВЫСШЕЕ             0   
9          0   -2188.756445         41              среднее             1   
10         2   -4171.483647         36               высшее             0   
11         0    -792.701887         40              среднее             1   
12         0            NaN         65              среднее             1   
13         0   -1846.641941         54  неоконченное высшее             2   
14         0   -1844.956182         56               высшее             0   
15         1    -972.364419         26              среднее             1   
16         0   -1719.934226         35              среднее             1   
17         0   -2369.999720         33               высшее             0   
18         0  400281.136913         53              среднее             1   
19         0  -10038.818549         48              СРЕДНЕЕ             1   

       family_status  family_status_id gender income_type  debt  \
0    женат / замужем                 0      F   сотрудник     0   
1    женат / замужем                 0      F   сотрудник     0   
2    женат / замужем                 0      M   сотрудник     0   
3    женат / замужем                 0      M   сотрудник     0   
4   гражданский брак                 1      F   пенсионер     0   
5   гражданский брак                 1      M   компаньон     0   
6    женат / замужем                 0      F   компаньон     0   
7    женат / замужем                 0      M   сотрудник     0   
8   гражданский брак                 1      F   сотрудник     0   
9    женат / замужем                 0      M   сотрудник     0   
10   женат / замужем                 0      M   компаньон     0   
11   женат / замужем                 0      F   сотрудник     0   
12  гражданский брак                 1      M   пенсионер     0   
13   женат / замужем                 0      F   сотрудник     0   
14  гражданский брак                 1      F   компаньон     1   
15   женат / замужем                 0      F   сотрудник     0   
16   женат / замужем                 0      F   сотрудник     0   
17  гражданский брак                 1      M   сотрудник     0   
18    вдовец / вдова                 2      F   пенсионер     0   
19         в разводе                 3      F   сотрудник     0   

     total_income                                 purpose  
0   253875.639453                           покупка жилья  
1   112080.014102                 приобретение автомобиля  
2   145885.952297                           покупка жилья  
3   267628.550329              дополнительное образование  
4   158616.077870                         сыграть свадьбу  
5   255763.565419                           покупка жилья  
6   240525.971920                       операции с жильем  
7   135823.934197                             образование  
8    95856.832424                   на проведение свадьбы  
9   144425.938277                 покупка жилья для семьи  
10  113943.491460                    покупка недвижимости  
11   77069.234271       покупка коммерческой недвижимости  
12            NaN                         сыграть свадьбу  
13  130458.228857                 приобретение автомобиля  
14  165127.911772              покупка жилой недвижимости  
15  116820.904450 

**Задание 3. Выведите основную информацию о датафрейме с помощью метода `info()`.**

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


## Предобработка данных

### Удаление пропусков

**Задание 4. Выведите количество пропущенных значений для каждого столбца. Используйте комбинацию двух методов.**

In [4]:
data.isna().sum()

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

**Задание 5. В двух столбцах есть пропущенные значения. Один из них — `days_employed`. Пропуски в этом столбце вы обработаете на следующем этапе. Другой столбец с пропущенными значениями — `total_income` — хранит данные о доходах. На сумму дохода сильнее всего влияет тип занятости, поэтому заполнить пропуски в этом столбце нужно медианным значением по каждому типу из столбца `income_type`. Например, у человека с типом занятости `сотрудник` пропуск в столбце `total_income` должен быть заполнен медианным доходом среди всех записей с тем же типом.**

In [5]:
for t in data['income_type'].unique():
    data.loc[(data['income_type'] == t) & (data['total_income'].isna()), 'total_income'] = \
    data.loc[(data['income_type'] == t), 'total_income'].median()

### Обработка аномальных значений

**Задание 6. В данных могут встречаться артефакты (аномалии) — значения, которые не отражают действительность и появились по какой-то ошибке. таким артефактом будет отрицательное количество дней трудового стажа в столбце `days_employed`. Для реальных данных это нормально. Обработайте значения в этом столбце: замените все отрицательные значения положительными с помощью метода `abs()`.**

In [6]:
data['days_employed'] = data['days_employed'].abs()

**Задание 7. Для каждого типа занятости выведите медианное значение трудового стажа `days_employed` в днях.**

In [7]:
data.groupby('income_type')['days_employed'].agg('median')

income_type
безработный        366413.652744
в декрете            3296.759962
госслужащий          2689.368353
компаньон            1547.382223
пенсионер          365213.306266
предприниматель       520.848083
сотрудник            1574.202821
студент               578.751554
Name: days_employed, dtype: float64

У двух типов (безработные и пенсионеры) получатся аномально большие значения. Исправить такие значения сложно, поэтому оставьте их как есть.

**Задание 8. Выведите перечень уникальных значений столбца `children`.**

In [8]:
data['children'].unique()

array([ 1,  0,  3,  2, -1,  4, 20,  5], dtype=int64)

**Задание 9. В столбце `children` есть два аномальных значения. Удалите строки, в которых встречаются такие аномальные значения из датафрейма `data`.**

In [9]:
data = data[(data['children'] != -1) & (data['children'] != 20)]

**Задание 10. Ещё раз выведите перечень уникальных значений столбца `children`, чтобы убедиться, что артефакты удалены.**

In [10]:
data['children'].unique()

array([1, 0, 3, 2, 4, 5], dtype=int64)

### Удаление пропусков (продолжение)

**Задание 11. Заполните пропуски в столбце `days_employed` медианными значениями по каждого типа занятости `income_type`.**

In [11]:
for t in data['income_type'].unique():
    data.loc[(data['income_type'] == t) & (data['days_employed'].isna()), 'days_employed'] = \
    data.loc[(data['income_type'] == t), 'days_employed'].median()

**Задание 12. Убедитесь, что все пропуски заполнены. Проверьте себя и ещё раз выведите количество пропущенных значений для каждого столбца с помощью двух методов.**

In [12]:
data.isna().sum()

children            0
days_employed       0
dob_years           0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

### Изменение типов данных

**Задание 13. Замените вещественный тип данных в столбце `total_income` на целочисленный с помощью метода `astype()`.**

In [13]:
data['total_income'] = data['total_income'].astype(int)

### Обработка дубликатов

**Задание 14. Обработайте неявные дубликаты в столбце `education`. В этом столбце есть одни и те же значения, но записанные по-разному: с использованием заглавных и строчных букв. Приведите их к нижнему регистру.**

In [14]:
data['education'] = data['education'].str.lower()

**Задание 15. Выведите на экран количество строк-дубликатов в данных. Если такие строки присутствуют, удалите их.**

In [15]:
data.duplicated().sum()

71

In [16]:
data = data.drop_duplicates()

### Категоризация данных

**Задание 16. На основании диапазонов, указанных ниже, создайте в датафрейме `data` столбец `total_income_category` с категориями:**

- 0–30000 — `'E'`;
- 30001–50000 — `'D'`;
- 50001–200000 — `'C'`;
- 200001–1000000 — `'B'`;
- 1000001 и выше — `'A'`.


**Например, кредитополучателю с доходом 25000 нужно назначить категорию `'E'`, а клиенту, получающему 235000, — `'B'`. Используйте собственную функцию с именем `categorize_income()` и метод `apply()`.**

In [17]:
def categorize_income(income):
    try:
        if 0 <= income <= 30000:
            return 'E'
        elif 30001 <= income <= 50000:
            return 'D'
        elif 50001 <= income <= 200000:
            return 'C'
        elif 200001 <= income <= 1000000:
            return 'B'
        elif income >= 1000001:
            return 'A'
    except:
        pass

In [18]:
data['total_income_category'] = data['total_income'].apply(categorize_income)

**Задание 17. Выведите на экран перечень уникальных целей взятия кредита из столбца `purpose`.**

In [19]:
data['purpose'].unique()

array(['покупка жилья', 'приобретение автомобиля',
       'дополнительное образование', 'сыграть свадьбу',
       'операции с жильем', 'образование', 'на проведение свадьбы',
       'покупка жилья для семьи', 'покупка недвижимости',
       'покупка коммерческой недвижимости', 'покупка жилой недвижимости',
       'строительство собственной недвижимости', 'недвижимость',
       'строительство недвижимости', 'на покупку подержанного автомобиля',
       'на покупку своего автомобиля',
       'операции с коммерческой недвижимостью',
       'строительство жилой недвижимости', 'жилье',
       'операции со своей недвижимостью', 'автомобили',
       'заняться образованием', 'сделка с подержанным автомобилем',
       'получение образования', 'автомобиль', 'свадьба',
       'получение дополнительного образования', 'покупка своего жилья',
       'операции с недвижимостью', 'получение высшего образования',
       'свой автомобиль', 'сделка с автомобилем',
       'профильное образование', 'высшее об

**Задание 18. Создайте функцию, которая на основании данных из столбца `purpose` сформирует новый столбец `purpose_category`, в который войдут следующие категории:**

- `'операции с автомобилем'`,
- `'операции с недвижимостью'`,
- `'проведение свадьбы'`,
- `'получение образования'`.

**Например, если в столбце `purpose` находится подстрока `'на покупку автомобиля'`, то в столбце `purpose_category` должна появиться строка `'операции с автомобилем'`.**

**Используйте собственную функцию с именем `categorize_purpose()` и метод `apply()`. Изучите данные в столбце `purpose` и определите, какие подстроки помогут вам правильно определить категорию.**

In [20]:
def categorize_purpose(row):
    try:
        if 'автом' in row:
            return 'операции с автомобилем'
        elif 'жил' in row or 'недвиж' in row:
            return 'операции с недвижимостью'
        elif 'свад' in row:
            return 'проведение свадьбы'
        elif 'образов' in row:
            return 'получение образования'
    except:
        return 'нет категории'

In [21]:
data['purpose_category'] = data['purpose'].apply(categorize_purpose)

### Шаг 3. Исследуйте данные и ответьте на вопросы

#### 3.1 Есть ли зависимость между количеством детей и возвратом кредита в срок?

In [22]:
#data.head(15)# Ваш код будет здесь. Вы можете создавать новые ячейки.
debt_sum = data.groupby('children')['debt'].sum()
category_count = data.groupby('children')['children'].count()
relatively_category = debt_sum / category_count * 100
df_children = [[0, 1063, 14091, 7.543822], [1, 444, 4808, 9.234609], [2, 194, 2052, 9.454191], [3, 27, 330, 8.181818], [4, 4, 41, 9.756098]]
col_children = ['children', 'debt_sum', 'category_count', 'relatively_category']
data_children = pd.DataFrame(data=df_children, columns=col_children)
data_children

children  debt_sum  category_count  relatively_category
0         0      1063           14091             7.543822
1         1       444            4808             9.234609
2         2       194            2052             9.454191
3         3        27             330             8.181818
4         4         4              41             9.756098

In [23]:
data_tab = data.groupby('children').agg({'debt': ['sum'], 'children': ['count']})
data_tab['relatively_category'] = debt_sum / category_count * 100
data_tab

debt children relatively_category
           sum    count                    
children                                   
0         1063    14091            7.543822
1          444     4808            9.234609
2          194     2052            9.454191
3           27      330            8.181818
4            4       41            9.756098
5            0        9            0.000000

**Вывод:** Количество детей не сильно влияет на возврат кредита в срок. Процент долга от обшего числа кредита показывает, что сильной зависимовти не наблюдается, хотя наименьший процент долга у категории с 0 детьми. Вероятно у лудей без детей есть больше возможности позволить себе кредит, не имея дополнительных трат связанных с детьми. Категория с 5 детьми не может рассматриваться в данном выводе, т.к. таких семей слишком мало, чтобы сравнивать с остальными.

#### 3.2 Есть ли зависимость между семейным положением и возвратом кредита в срок?

In [24]:
debt_sum = data.groupby('family_status')['debt'].sum()# Ваш код будет здесь. Вы можете создавать новые ячейки.
credit_count = data.groupby('family_status')['family_status'].count()
relatively = (debt_sum / credit_count)*100
df = [['Не женат / не замужем', 273, 2796, 9], ['в разводе', 84, 1189, 7], ['вдовец / вдова', 63, 951, 6], ['гражданский брак', 385, 4134, 9], ['женат / замужем', 927, 12261, 7]]
columns = ['family_status', 'debt_sum', 'credit_count', 'relatively']
info = pd.DataFrame(data=df, columns=columns)
info.sort_values(by='relatively', ascending=False)

family_status  debt_sum  credit_count  relatively
0  Не женат / не замужем       273          2796           9
3       гражданский брак       385          4134           9
1              в разводе        84          1189           7
4        женат / замужем       927         12261           7
2         вдовец / вдова        63           951           6

In [25]:
data_tab2 = data.groupby('family_status').agg({'debt': ['sum'], 'family_status': ['count']})
data_tab2['relatively'] = relatively
data_tab2.sort_values('relatively')

debt family_status relatively
                       sum         count           
family_status                                      
вдовец / вдова          63           951   6.624606
в разводе               84          1189   7.064760
женат / замужем        927         12261   7.560558
гражданский брак       385          4134   9.313014
Не женат / не замужем  273          2796   9.763948

**Вывод:** На супружеские пары приходится больше всего долга, но именно эта категория чаще всего берет кредиты. После того как посчитали относительную метрику стало ястно, что явной зависимости долга от семейного положения нет.

#### 3.3 Есть ли зависимость между уровнем дохода и возвратом кредита в срок?

In [26]:
data.head()# Ваш код будет здесь. Вы можете создавать новые ячейки.
category_sum = data.groupby('total_income_category')['debt'].sum()
category_count = data.groupby('total_income_category')['total_income_category'].count()
category_relatively = category_sum / category_count * 100
print(category_sum.sort_values())
print(category_count.sort_values())
print(category_relatively.sort_values())
data_total = [['B', 354, 5014, 7.060231], ['C', 1353, 15921, 8.498210], ['D', 21, 349, 6.017192]]
columns = ['total_income_category', 'category_sum', 'category_count', 'category_relatively']
info = pd.DataFrame(data=data_total, columns=columns)
info.sort_values(by='category_relatively')

total_income_category
A       2
E       2
D      21
B     354
C    1353
Name: debt, dtype: int64
total_income_category
E       22
A       25
D      349
B     5014
C    15921
Name: total_income_category, dtype: int64
total_income_category
D    6.017192
B    7.060231
A    8.000000
C    8.498210
E    9.090909
dtype: float64


total_income_category  category_sum  category_count  category_relatively
2                     D            21             349             6.017192
0                     B           354            5014             7.060231
1                     C          1353           15921             8.498210

**Вывод:** Мы убрали из анализ группы А и Е т.к. их в сравнении слишком мало. Делаем вывод, что заемшики с дохом от 30000 до 50000 (группа D) наиболее ответственны в погошении кредита.

In [27]:
data_tab3 = data.groupby('total_income_category').agg({'debt': ['sum'], 'total_income_category': ['count']})
data_tab3['category_relatively'] = category_relatively
data_tab3.sort_values('category_relatively')

debt total_income_category category_relatively
                        sum                 count                    
total_income_category                                                
D                        21                   349            6.017192
B                       354                  5014            7.060231
A                         2                    25            8.000000
C                      1353                 15921            8.498210
E                         2                    22            9.090909

Уберем из таблицы категории которые не влияют на общую картину. Это категории D, A, E и оставим только те которые имеют более конкурентные значения.

In [28]:
data_tab3.columns
data_tab3 = data_tab3.loc[data_tab3[('total_income_category', 'count')] > 1000]
data_tab3['category_relatively'] = category_relatively
data_tab3

debt total_income_category category_relatively
                        sum                 count                    
total_income_category                                                
B                       354                  5014            7.060231
C                      1353                 15921            8.498210

#### 3.4 Как разные цели кредита влияют на его возврат в срок?

In [29]:
purpose_debt = data.groupby('purpose_category')['debt'].sum()
purpose_count = data.groupby('purpose_category')['purpose_category'].count()
purpose_relatively = purpose_debt / purpose_count * 100# Ваш код будет здесь. Вы можете создавать новые ячейки.
data_total = [['операции с автомобилем', 400, 4279, 9.347978], ['операции с недвижимостью', 780, 10751, 7.255139], ['получение образования', 369, 3988, 9.252758], ['проведение свадьбы', 183, 2313, 7.911803]]
columns = ['purpose_category', 'purpose_debt', 'purpose_count', 'purpose_relatively']
info = pd.DataFrame(data=data_total, columns=columns)
info.sort_values(by='purpose_relatively')

purpose_category  purpose_debt  purpose_count  purpose_relatively
1  операции с недвижимостью           780          10751            7.255139
3        проведение свадьбы           183           2313            7.911803
2     получение образования           369           3988            9.252758
0    операции с автомобилем           400           4279            9.347978

In [30]:
data_tab4 = data.groupby('purpose_category').agg({'debt': ['sum'], 'purpose_category': ['count']})
data_tab4['purpose_relatively'] = purpose_relatively
data_tab4.sort_values('purpose_relatively')

debt purpose_category purpose_relatively
                          sum            count                   
purpose_category                                                 
операции с недвижимостью  780            10751           7.255139
проведение свадьбы        183             2313           7.911803
получение образования     369             3988           9.252758
операции с автомобилем    400             4279           9.347978

**Вывод:** Заемщики из категорий "операции с недвижимостью" и "проведение свадьбы" имеют наименьший процент невыплат по кредиту. Можно сделать вывод, что люди готовящиеся к свадьбе и нацеленные на покупку жилья более исполнительны.

#### 3.5 Приведите возможные причины появления пропусков в исходных данных.

*Ответ:* Пропуски в данных могут возникнуть по нескольким причинам. Они могут исчезнкть при выводе или копировании данных, т.е. по техническим причинам. В других случаях заемшик не желает указывать свои личные данные.

#### 3.6 Объясните, почему заполнить пропуски медианным значением — лучшее решение для количественных переменных.

*Ответ:* Количественные переменные могут сильно отличаться друг от друга. Так, например, доходы разных категорий граждан могут иметь далекие друг от друга значения и если посчитать среднее значение можно сильно исказить истинные данные. Медианное значение наиболее подходит в таких случаях, т.к. имеет лучшее представление об истинности значений.

### Шаг 4: общий вывод.

Супружеские пары, которые только готовятся к покупке жилья (и) или планирующие детей являются перспективнее т.к. они более ответственны в выплате долга по кредиту. Также на погашение кредита влияет заработок граждан и заемщики с доходами от 30000 до 50000 реже задерживают выплаты. Эта  же категория граждан является самой крупной т.к. такие зарплаты наиболее распространенные по стране. 

В процессе работы над проектом проводились исследования и проверялись гипотизы такие как:
    
- Есть ли зависимость между количеством детей и возвратом кредита в срок?
    
Заемщики без детей реже остаются должниками. Заемщики из категории с 1 ребенком исполнительней чем с 2 детьми, преимущество в 0,22 процента. Но в данном иследовании пришлось откинуть категории с 3, 4 и 5 детьми, так как их слишком мало по сравнению с остальными категориями заемщиков.
    
- Есть ли зависимость между семейным положением и возвратом кредита в срок?
    
Самая многочисленная категория это "женат / замужем" которых в данном иследовании 12261. А самая малочисленная "вдовец / вдова" 951. Но если сравнить процент долга от заема по которому становится ясно, что люди, которые еще не были в официальном браке, имеют мало опыта в данной сфере и не совсем еще осознают ответственность.
    
- Есть ли зависимость между уровнем дохода и возвратом кредита в срок?
    
В этом анализе снова пришлось избавиться от самых малочисленных категорий. Тогда стало ясно, что чем выше доход тем легче справиться с погашением кредита.
    
- Как разные цели кредита влияют на его возврат в срок?
    
Люди готовящиеся к свадьбе и нацеленные на покупку жилья более исполнительны. Заемщики из категорий "операции с недвижимостью" и "проведение свадьбы" имеют наименьший процент невыплат по кредиту. Разница в проценте долга между данными категориями и остальными составляет примерно 1.75 процентов.
    
В любом исследовании сначала необходимо проверяять данные т.к. всегда могут встретиться ошибки или пропуски. А всретив их необходимо разрешить, чему я и научилась в данном проекте.</div>